# Generated by Django 2.0 on 2017-12-10 23:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('3011179f-aaa4-43b0-b001-294984111a19'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('release_year', models.IntegerField()),
                ('cut', models.CharField(max_length=250)),
                ('resolution', models.CharField(max_length=250)),
                ('date_added', models.DateField()),
                ('length_minutes', models.IntegerField()),
                ('path', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('820a9f00-c619-4da6-a3e0-fec0b37a41ef'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('season', models.IntegerField()),
                ('cut', models.CharField(max_length=250)),
                ('resolution', models.CharField(max_length=250)),
                ('date_added', models.DateField()),
                ('path', models.TextField()),
            ],
        ),
    ]
