# Generated by Django 2.0 on 2017-12-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('release_year', models.IntegerField()),
                ('cut', models.CharField(max_length=250)),
                ('resolution', models.CharField(max_length=250)),
                ('date_added', models.DateField()),
                ('length_minutes', models.IntegerField()),
                ('path', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('season', models.IntegerField()),
                ('cut', models.CharField(max_length=250)),
                ('resolution', models.CharField(max_length=250)),
                ('date_added', models.DateField()),
                ('path', models.TextField()),
            ],
        ),
    ]
